### ISSUE TITLE
Startup error.

### ISSUE THREAD

**Issue by MariusMRN** [BlockHorizons/BlockSniper#104]
#### Description
This error appear when i m starting the server and also disable the plugin.

#### Versions
* PocketMine version: 3.2.2
* BlockSniper version: last ( updated 1h ago )
* Game version: PE/W10

#### Crashdump and/or console errors

http://prntscr.com/ks5vfm

**Comment by Sandertv** [comment]
Please download the plugin from Poggit or `git clone --recursive`. Downloading the ZIP from GitHub will not work.
