### ISSUE TITLE
Non-admin players unable to change brush type or shape after reloading the server.

### ISSUE THREAD

**Issue by ItzBlue72** [BlockHorizons/BlockSniper#136]
#### Description
I have this issue on my server where players who aren't operators are unable to select the brush type and shape in the GUI and they show up as as blank. This occurs after reloading the server.
![blocksnipernotworking](https://user-images.githubusercontent.com/29171372/81774689-0e129b00-94a0-11ea-8ead-beeeb0769c2c.jpg)

#### Versions
* PocketMine version: PocketMine-MP 3.12.0
* BlockSniper version: v3.2.3
* Minecraft version: Bedrock Edition v.1.14.60 (protocol version 390)

#### Crashdump and/or console errors
```
No console errors or crash.
```

**Comment by SOF3** [comment]
What do you mean by reloading the server? If you are referring to the `/reload` command, this command has problems with most plugins. (It is going to be removed from PocketMine soon)

**Comment by ItzBlue72** [comment]
Ah, didn't know `/reload` was causing issues and that it's going to be removed.
