### ISSUE TITLE
Overlay affects water aswell.

### ISSUE THREAD

**Issue by TechnicalBro** [BlockHorizons/BlockSniper#138]
#### Description

- When overlaying, water is overlayed aswell. This should not be default behaviour. 

#### Versions
* PocketMine version: latest
* BlockSniper version: latest
* Minecraft version: latest

#### Crashdump and/or console errors

```
```

**Comment by Sandertv** [comment]
Thanks for the bug report. Going to merge this with #131 as it is the same issue.
