### ISSUE TITLE
Share your templates!

### ISSUE THREAD

**Issue by Sandertv** [BlockHorizons/BlockSniper#14]
As of pull request #11, BlockSniper has the so called 'templates' implemented. Templates can be made using the `/clone template <radiusXheight> <name>` command. Using this command, BlockSniper will save the selection to a file in the directory `/plugins/BlockSniper/templates/`. Here comes the best thing. Templates can be shared by downloading it and uploading it for your friends.

This is the place you can upload templates for others to download on their servers. They can then use the `/paste template <name>` to paste that building in the world. To install a template, simply download one here and put it in the `/plugins/BlockSniper/templates/` folder. As long as the template is appropriate, feel free to upload it here if you want.

It would be best if you could provide a picture of the template here as well. Have fun using the templates feature!

**Comment by Sandertv** [comment]
I'll upload a first one. 

This template adds a very cool (built by me) large mansion to your world. You can paste it by installing it on your server by putting it in the templates folder and doing /paste template Mansion. It will then create this building on the target block:
![screenshot_2017-01-31-11-20-06](https://cloud.githubusercontent.com/assets/16114089/22461148/64aa02f8-e7a8-11e6-83be-7a00c3b000cf.png)

Download:
http://www.mediafire.com/?8mefuakpcgflyx5

**Comment by HimbeersaftLP** [comment]
WOAH

**Comment by Mrfanman345** [comment]
Any specific templates people want? I have a few I may upload tomorrow but want to see if anyone has a request.

**Comment by Sandertv** [comment]
Here's another one ^^
This template adds a large mountain, which was made using the features of BlockSniper. The types used are Fill, melt, replace and overlay. You can install it by putting it in the templates folder and doing `/paste template LargeMountain`. It will then create this mountain:
![screenshot_2017-02-05-21-08-18](https://cloud.githubusercontent.com/assets/16114089/22629411/e8175ed8-ebe5-11e6-8186-99c060b69364.png)

Download: http://www.mediafire.com/file/4s9ecrnidl0ik8t/LargeMountain.yml

**Comment by HimbeersaftLP** [comment]
Ughh, Mediafire

**Comment by Sandertv** [comment]
What's the matter with it? :P

**Comment by HimbeersaftLP** [comment]
I hate it, it's impossible to download something from Medifire without having 1000000 popups open in the background (except if h are using an adblocker lol)

**Comment by Sandertv** [comment]
Kinda true... Ah whatever, it should do :)

**Comment by WreckagePE** [comment]
Can you do a tutorial on how to make the large mountain? I'm trying to create terrain like that :). It's very hard for me... Also, can you implement gravitational spheres?

**Comment by Sandertv** [comment]
The gravity shapes will be a feature soon, but it's very tough to implement. I can try to make a video on how to make these mountains.

**Comment by Sandertv** [comment]
@WreckagePE I made a video on how to make one at: https://youtu.be/G3SB8ZNpphI
The editing is terrible and the FPS might drop at times, but you should be able to follow it.

**Comment by KairusDarkSeeker** [comment]
@Sandertv how do I make a template? I'm not good at reading wikis

**Comment by Sandertv** [comment]
Basically what you do is look at the middle of your building, at the bottom layer of it, and then type /clone template <radiusXheight> <name>

Then you can do /paste template <name>

**Comment by KairusDarkSeeker** [comment]
Oh okay

**Comment by SOF3** [comment]
Are you gonna create an online repository for the templates? Might be a good idea to download them upon request (like `/install-template sandertv/mansion`) :D

**Comment by Sandertv** [comment]
I'm actually thinking of deprecating them because version 1.4 will have schematics implemented, which are more useful for cross platform sharing. :P

**Comment by DarkGoldKnight** [comment]
I've got an old template of a steampunk build, which was built back in 0.15.
If in doubt, feel free to edit anything.
