### ISSUE TITLE
Changelog causes a crash on startup

### ISSUE THREAD

**Issue by JustinLLDV** [BlockHorizons/BlockSniper#155]
Changelog doesn't work anymore because this link is invalid: 
https://raw.githubusercontent.com/BlockHorizons/BlockSniper/API-4.0.0/CHANGELOG.md

The plugin requires it here:
https://github.com/BlockHorizons/BlockSniper/blob/master/src/BlockHorizons/BlockSniper/changelog/ChangelogTask.php#L13

Otherwise this crash will happen:
`2022-08-01 [11:50:46.776] [Server thread/CRITICAL]: ErrorException: "Undefined array key "4.0.0"" (EXCEPTION) in "plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/session/PlayerSession" at line 114
--- Stack trace ---
  #0 plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/session/PlayerSession(114): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[27] Undefined array key "4.0.0", string[121] phar:///home/clientservers/server-402647/plugins/BlockSniper.phar/src/BlockHoriz, int 114)
  #1 plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/session/PlayerSession(55): BlockHorizons\BlockSniper\session\PlayerSession->sendChangelog()
  #2 plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/session/Session(51): BlockHorizons\BlockSniper\session\PlayerSession->initializeBrush()
  #3 plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/session/PlayerSession(33): BlockHorizons\BlockSniper\session\Session->__construct(object BlockHorizons\BlockSniper\session\owner\PlayerSessionOwner#124625, object BlockHorizons\BlockSniper\Loader#28827)
  #4 plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/session/SessionManager(45): BlockHorizons\BlockSniper\session\PlayerSession->__construct(object BlockHorizons\BlockSniper\session\owner\PlayerSessionOwner#124625, object BlockHorizons\BlockSniper\Loader#28827)
  #5 plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/session/SessionManager(31): BlockHorizons\BlockSniper\session\SessionManager::createPlayerSession(string[11] ItsFlameoYt, object BlockHorizons\BlockSniper\Loader#28827)
  #6 plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/listener/BrushListener(231): BlockHorizons\BlockSniper\session\SessionManager::getPlayerSession(object pocketmine\player\Player#115674)
  #7 pmsrc/src/event/RegisteredListener(60): BlockHorizons\BlockSniper\listener\BrushListener->onItemHeld(object pocketmine\event\player\PlayerItemHeldEvent#129077)
  #8 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerItemHeldEvent#129077)
  #9 pmsrc/src/player/Player(1434): pocketmine\event\Event->call()
  #10 pmsrc/src/network/mcpe/handler/InGamePacketHandler(539): pocketmine\player\Player->selectHotbarSlot(int 7)
  #11 pmsrc/vendor/pocketmine/bedrock-protocol/src/MobEquipmentPacket(59): pocketmine\network\mcpe\handler\InGamePacketHandler->handleMobEquipment(object pocketmine\network\mcpe\protocol\MobEquipmentPacket#115385)
  #12 pmsrc/src/network/mcpe/NetworkSession(394): pocketmine\network\mcpe\protocol\MobEquipmentPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#121424)
  #13 pmsrc/src/network/mcpe/NetworkSession(357): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\MobEquipmentPacket#115385, string[23] ....@..................)
  #14 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[67] .Wda@.....X.@,.. ;;......^.....?...E...~1v8.T.....8........z....I..)
  #15 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[76] .....7._..>.mk.3...N...."io....F....w......u...^......%P....,.k.g...>.q.xk .)
  #16 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#32681)
  #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #19 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1659347446.7957)
  #20 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #21 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[34] /home/clientservers/server-402647/, string[42] /home/clientservers/server-402647/plugins/)
  #22 pmsrc/src/PocketMine(327): pocketmine\server()
  #23 pmsrc(11): require(string[71] phar:///home/serversoftwares/PocketMine_1.19.10.phar/src/PocketMine.php)
--- End of exception information ---`

**Comment by Ifera** [comment]
Thanks for reporting, the issue has been fixed!
