### ISSUE TITLE
Some New Ideas

### ISSUE THREAD

**Issue by KevinLong021** [BlockHorizons/BlockSniper#22]
#### Description

This is more of a list of suggestions than an issue. Feel free to ask me any questions you have about any of these ideas. :)

#### Suggested New Features

 - Gravity Shapes: Shapes that are made out of the selected block(s) that are affected by gravity like sand but aren't sand and after the initial summoning retain the specified blocks properties.
  + Example: All shapes can be affected by gravity by adding a g to the front of the name. (gsphere, gcylinder, etc.)
 - Decreasing Brush Mode: A brush mode that decreases the shape size by the selected interval after each use.
  + Example: The original brush size is set to a 7 after each use it decreases by 1 size and at 0 resets to 7. You probably would want to send a chat message saying that it reset to avoid accidentally using the brush one too many times.
#### Commands
Decreasing Brush Size
```
/dbrush [block(s)] [shape] [starting size] [ending size] [interval of decrease]
```
#### Versions
* PocketMine version: 
* BlockSniper version: Latest/Self Compiled
* Game version: PE/W10 - PE 1.0.2

#### Crashdump and/or console errors

```
None
```

**Comment by Sandertv** [comment]
Nice ideas! Wow! For the gravity ones, how exactly did you visualize it? For example if you brush a ball, that every block made will appear on the first block above the ground?

**Comment by Mrfanman345** [comment]
Yes. Like if you were to use a sphere made out of sand, any block not on top of a solid block would fall until it lands on one.

**Comment by Sandertv** [comment]
I really like that idea. I'm not going to make it show the falling block entity though, as that would lag too much.

**Comment by Mrfanman345** [comment]
Ya that would be a lot of lag.

**Comment by Sandertv** [comment]
I'll be pushing the changes to a 1.1.0 branch once there's some stuff done. I'm working on the gravity option now. I love the idea!

**Comment by MrKiaN** [comment]
Can u Add Example For Commands :(

**Comment by Sandertv** [comment]
Take a look at the Wiki, it should clarify a lot.

**Comment by Sandertv** [comment]
I'm going to move these things to a new issue with a TODO list for 1.1.0 update :) The Decrementing brush is working on the 1.1.0 branch btw, you might want to check it out.

**Comment by TheDeibo** [comment]
Might I suggest adding a hollow option?

For example, a hollow sphere. 
the shape names could be
 - hcube
 - hsphere
 - hcuboid
 - hcylinder

**Comment by Sandertv** [comment]
I should probably do that. Maybe it would be easier with a new brush parameter though, for example: /b hollow 1.

**Comment by TheDeibo** [comment]
How about a /b reset
So it resets command to default value 
(like when the server resets)

it would be handy, when making stuff :)

**Comment by Sandertv** [comment]
Nice idea, I'll add that soon.

**Comment by Sandertv** [comment]
/b reset has been implemented, hollow cubes, cuboids, cylinders and spheres have been implemented. Hollow spheres and cylinders were a pain to find the nice ratios for, so about 20 commits in the 1.3.0 branch are from those. Anyways, hollow shapes are to be found in the 1.3.0 branch.

**Comment by Sandertv** [comment]
You can make the shapes hollow by doing /b hollow 1 (or /b ho 1) and to disable: /b hollow 0.

**Comment by DanielAktas** [comment]
I LOVE THIS PLUGIN!!!

I just figured out how to save templates which is awesome but I am wishing that they could be saved in a schematics file type instead of a .yml so i could import and export them into and out of my server.

**Comment by Sandertv** [comment]
@DanielAktas I'll have a look into actual Schematics a bit more, and try to implement those. I'm very glad you like the plugin!

**Comment by Sandertv** [comment]
@DanielAktas 
Schematics are currently under heavy development. They'll (hopefully) be included soon.
