### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by BogdanMakarchuk** [BlockHorizons/BlockSniper#39]
#### Versions
* PocketMine version: 1.0.5 (Tesseract)
* BlockSniper version: 1.3.0
* Game version: PE

#### Crashdump and/or console errors

[PluGPluS] [20:44:52] > Enabling BlockSniper v1.3.0

Warning: yaml_parse_file(/root/pvp/plugins/BlockSniper/settings.yml): failed to open stream: No such file or directory in /root/pvp/plugins/BlockSniper-master/src/Sandertv/BlockSniper/data/ConfigData.php on line 18
[PluGPluS] [20:44:52] > [BlockSniper] [BlockSniper] Language selected: ru

**Comment by Sandertv** [comment]
Is the settings.yml file added in the plugins/BlockSniper folder?

**Comment by BogdanMakarchuk** [comment]
The file settings.yml was created! - Tesseract the latest version. Modifications no! Messages in the console to change the plugin

**Comment by Sandertv** [comment]
Can you try exceeding the limit in the settings.yml brush size, by just doing /b size 50 as a test?

**Comment by Sandertv** [comment]
Fixed locally, I'll push it to the repository once I'm done with the other changes. It's not a very critical issue.
