### ISSUE TITLE
brush command doesn't work since 1.1.0

### ISSUE THREAD

**Issue by Akuroma** [BlockHorizons/BlockSniper#58]
#### Description
When I try using the /brush command the error seen below is given to console.

#### Versions
* PocketMine version: PocketMine-MP 1.6.2dev 「Unleashed」
* BlockSniper version: Version: 1.3.4
* Game version: PE/W10

#### Crashdump and/or console errors

![image](https://user-images.githubusercontent.com/19476909/27144237-5bba8026-5131-11e7-89f3-3ef98d8f1e03.png)

**Comment by Sandertv** [comment]
/brush without any parameters is going to give an error. What is the exact command you're using?

**Comment by Akuroma** [comment]
Ah okay, I didn't knew. Is it possible to fix this? I've tried it with other parameters (/brush preset new). It works.

**Comment by Sandertv** [comment]
What exact command did you enter. To brush a big stone ball, you could use /b ty fill, /b si 7, /b bl stone, then get out the brush item (golden carrot by default) and start brushing.
