### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XDqrkneZ** [BlockHorizons/BlockSniper#59]
#### Description

I get this error when i use /brush, not only did /brush but /brush sphere too

07.07 18:40:47 [Server] Server thread/CRITICAL ErrorException: "Undefined offset: 0" (EXCEPTION) in "BlockSniper-master/src/BlockHorizons/BlockSniper/commands/BrushCommand" at line 34
07.07 18:40:47 [Server] Server thread/CRITICAL Unhandled exception executing command 'b' in brush: Undefined offset: 0
#### Versions
* PocketMine version:  PocketMine-MP 1.6.2dev [#70bd9af 2017-06-30] ���Unleashed��� implementing API version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)
* BlockSniper version: 1.3.4
* Game version: PE/W10

#### Crashdump and/or console errors

```
```

**Comment by Sandertv** [comment]
Please read the wiki.
