### ISSUE TITLE
how to set another language ?

### ISSUE THREAD

**Issue by totor29** [BlockHorizons/BlockSniper#65]
Hi,

I tried to set french language  on settings.yml but it does not work
Message-Language: "fr"
Is it correct  ?
thanks

**Comment by Sandertv** [comment]
That should work. Could you give me a couple messages that don't display in French?

**Comment by totor29** [comment]
With this setup on settings.yml
Message-Language: "fr"

i have this log : 

2017-08-10 [12:58:45] [Server thread/INFO]: [BlockSniper] [BlockSniper] No valid language selected, English has been auto-selected.
Please setup a language by using /blocksniper language <lang>.

English has been auto selected

**Comment by Sandertv** [comment]
Could you try entering that into the settings.yml again, then using /bs reload in the console, instead of restarting the server?

**Comment by Sandertv** [comment]
Either way this has been taken care of on a development branch, but since it uses methods not yet available on Minecraft PE 1.1, I do not recommend using it yet. This will be closed when that branch gets merged into master.

**Comment by Sandertv** [comment]
For now, try just stopping the server, then changing it, then starting the server again.
