### ISSUE TITLE
World Edit Schematic Paste issue

### ISSUE THREAD

**Issue by jasonwynn10** [BlockHorizons/BlockSniper#69]
#### Description

When running the command `/paste schematic Plot` I recieved the error along with the command arguments out of their input order

This is the schematic I was trying to import
[Plot.schematic](https://github.com/BlockHorizons/BlockSniper/files/1273601/Plot.schematic.txt)
 
#### Versions
* PocketMine version: API unlocked ALPHA7
* BlockSniper version: 1.4.0
* Game version: N/A

#### Crashdump and/or console errors

```
03.09 21:18:49 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected '<', expecting end of file" (EXCEPTION) in "src/pocketmine/utils/BlockIterator" at line 169
03.09 21:18:49 [Server] Server thread/CRITICAL Unhandled exception executing command 'paste Plot schematic' in paste: syntax error, unexpected '<', expecting end of file
```

**Comment by Sandertv** [comment]
That's an interesting error you have there, could you try reproducing that with debu level set to 2?

**Comment by jasonwynn10** [comment]
I can't get the debug to level 2 ;-;
its another person's server. I just have console access and said I would ask you to fix it 😋

**Comment by jasonwynn10** [comment]
The command ordering is so wierd when client command syntax is buing used

**Comment by Sandertv** [comment]
Yeah with the /paste schematic <name> command it becomes /paste Tree schematic instead of /paste schematic Tree. Anyway I'll look into it and see if I can find it.

**Comment by Sandertv** [comment]
Try the latest version.
