### ISSUE TITLE
DERTDADDY DIWSCOVERY SECRET MATH THAT OPTIMIZED THE GENISSY PRO 35% !

### ISSUE THREAD

**Issue by betty828** [BlockHorizons/BlockSniper#72]
SECRER MATH BE DISCOVER MAKE GENISYS FAST NOW 

BEFORE:
11 PLAYER = LAG

NOW
17 = LTTLE LAG

!!!!!!

PLEASE MAKE BLOCK SNIPER SUPPORT THE GENISYS PRO SO WE CAN CONTUINUE OPTIMIZE IT ! ITS NOT SELL THE PROFITS !

**Comment by Sandertv** [comment]
Fuck off Nycu, get a life.
