### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by PotatoeTrainYT** [BlockHorizons/BlockSniper#76]
#### Description

Im Trying To Make Custom Terrain For My Server So I Tried Using BlockSniper. When I Done /b It Brought Up The Menu, When I Selected An Option Nothing Came Up. I Recorded It: https://youtu.be/88J9k5k5tkg

#### Versions
* PocketMine version: ALPHA9
* BlockSniper version: Latest
* Game version: PE/W10

#### Crashdump and/or console errors

```N/A
```

**Comment by Sandertv** [comment]
Is there any error that shows up when using this command?

**Comment by PotatoeTrainYT** [comment]
no, none at all

**Comment by Sandertv** [comment]
I personally can't say I've been able to reproduce this. Where'd you get your phar file from?

**Comment by PotatoeTrainYT** [comment]
i downloaded recent zip and also recent release from poggit neither work

**Comment by Sandertv** [comment]
Could you please download the latest version here: https://poggit.pmmp.io/ci/BlockHorizons/BlockSniper/BlockSniper

And report back? There's always the latest phar files there. I don't recommend using the zip.

**Comment by Sandertv** [comment]
I'm unable to reproduce this using the latest version. Please don't hesitate to mention me if this is not fixed for you.
