### ISSUE TITLE
Nothing works on it.

### ISSUE THREAD

**Issue by DroidPlaysM** [BlockHorizons/BlockSniper#78]
When bringing up the brush menu we try and click on a button nothing happens. There is no errors or anything.

**Comment by Sandertv** [comment]
Using the poggit release or the latest build?

**Comment by DroidPlaysM** [comment]
poggit and the latest build on github tested both still don't work

**Comment by DroidPlaysM** [comment]
Sorry i found the issue it was crossing over my other menu plugins. Sorry for bothering you.
