### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by QuiverlyRivalry** [BlockHorizons/BlockSniper#79]
How to use schematics

**Comment by Sandertv** [comment]
To use schematics you just download the schematic to your likes from the internet. (There are a lot of those, just search on PlanetMinecraft for example) Then put the .schematic file in the BlockSniper/schematics/ folder with the desired name, and finally go in-game and use /schematic paste <schematic file name without .schematic>

**Comment by Sandertv** [comment]
The schematic should then pop up on the location you look at. If you have problems with it feel free to ask for some more clarification.

**Comment by QuiverlyRivalry** [comment]
k thx ill try this

**Comment by QuiverlyRivalry** [comment]
there is no such commqnd..

**Comment by Sandertv** [comment]
Oops sorry, /paste schematic <name>

**Comment by QuiverlyRivalry** [comment]
doesnt paste.. 
https://www.planetminecraft.com/project/kayt-the-floating-castle-download/

**Comment by QuiverlyRivalry** [comment]
None of the schematics work..

**Comment by Sandertv** [comment]
Big schematics take some time to paste. Don't expect it to happen in an instance. If you turn debug level to 2 in the pocketmine.yml you can see the progress.

**Comment by QuiverlyRivalry** [comment]
21.10 11:29:25 [Server] INFO Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes) in phar:///custom-php7.2.phar/src/pocketmine/block/BlockFactory.php on line 384
21.10 11:29:25 [Server] Server thread/CRITICAL Could not execute asynchronous task PasteTask: Task crashed
21.10 11:29:26 [Server] INFO Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 12288 bytes) in phar:///custom-php7.2.phar/src/pocketmine/level/format/Chunk.php on line 1002
21.10 11:29:26 [Server] Server thread/CRITICAL Could not execute asynchronous task ChunkRequestTask: Task crashed
21.10 11:29:29 [Server] INFO Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes) in phar:///custom-php7.2.phar/src/pocketmine/level/format/Chunk.php on line 1002
21.10 11:29:29 [Server] Server thread/CRITICAL Could not execute asynchronous task ChunkRequestTask: Task crashed

**Comment by Sandertv** [comment]
... Which means the schematic was too big to execute. I'll work on doing this in such a way that the least memory gets consumed soon.

**Comment by QuiverlyRivalry** [comment]
So, I cant paste that scheme .-.

**Comment by Sandertv** [comment]
In fact... What you COULD try, is setting the async worker memory limit higher. I can't promise that'll make it work, but it might.
