### ISSUE TITLE
[Feature Request] Option for 2 Position Selections

### ISSUE THREAD

**Issue by 95CivicSi** [BlockHorizons/BlockSniper#83]
#### Description

The clone command (and several brush options) would greatly benifit if the user could select 2 positions (Lower Corner and opposing Upper Corner blocks) instead of radius.  

For the clone command, this would reduce iteration through unneccessary spaces and make for more accurate duplications when cloning items that were built in normal terrain instead of a flat world.

For brushes (eg drain, fill, tree), a 2 position selection would make it possible to create vertical structures such as walls or select areas where a rectangular shape would be more useful.

#### Versions
* PocketMine version: 1.7dev-345
* BlockSniper version: 2.2.1 (dev 292)
* Game version: W10

**Comment by Sandertv** [comment]
Going to be redoing this probably in a version 3.1.o after the 3.0.0 version is finished. The earlier implementation was quite messy.

**Comment by Sandertv** [comment]
This is now (finally!) done. You can try it out in the 3.2.0 version I am about to release.
