### ISSUE TITLE
Incompatible API Version

### ISSUE THREAD

**Issue by KevinLong021** [BlockHorizons/BlockSniper#91]
#### Description

When I try loading BlockSniper (2.0.0) on my server it gives me the message in the code block below.
#### Versions
* PocketMine version: 3.0.3
* BlockSniper version: 2.0.0
* Game version: **PE**/W10

#### Crashdump and/or console errors

```
[15:19:18] [Server thread/ERROR]: Could not load plugin 'BlockSniper': Incompatible API version (plugin requires one of: 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9)
```

**Comment by Sandertv** [comment]
https://github.com/BlockHorizons/BlockSniper/commit/10dccd00a4901e66f1a6824e13cc2d587dde2f7a
